version: 2

registries:
  inkcre-github-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    scope: '@inkcre'
    token: ${{ secrets.INKCRE_PACKAGES_READ_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    registries:
      - inkcre-github-packages
    open-pull-requests-limit: 3
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - '*'
