packages:
  - packages/*
  - apps/*
  - extensions/*

catalog:
  typescript: 5.9.3
  vue-tsc: 3.3.8

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  spawn-sync: true
  vue-demi: true
  workerd: false

overrides:
  '@babel/core@<=7.29.0': 7.29.7
  adm-zip@<0.6.0: 0.6.0
  brace-expansion@>=4.0.0 <5.0.9: 5.0.9
  defu@<=6.1.4: 6.1.7
  esbuild@>=0.27.3 <0.28.1: 0.28.1
  fast-uri@>=3.0.0 <3.1.5: 3.1.5
  immutable@>=5.0.0-beta.1 <5.1.8: 5.1.8
  js-yaml@>=4.0.0 <4.3.1: 4.3.1
  koa@>=3.0.0 <3.1.2: 3.1.2
  nanoid@>=3.0.0 <3.3.18: 3.3.18
  nanoid@>=4.0.0 <5.1.16: 5.1.16
  picomatch@<2.3.2: 2.3.2
  picomatch@>=4.0.0 <4.0.4: 4.0.5
  postcss@<=8.5.17: 8.5.18
  rollup@>=4.0.0 <4.59.0: 4.59.0
  shell-quote@<=1.8.4: 1.9.0
  tmp@<0.2.7: 0.2.7
  uuid@<11.1.1: 11.1.1
  ws@>=8.0.0 <8.21.0: 8.21.0

minimumReleaseAgeExclude:
  - '@inkcre/ui-web@1.4.0'
  - '@supabase/cli-darwin-arm64@2.112.0'
  - '@supabase/cli-darwin-x64@2.112.0'
  - '@supabase/cli-linux-arm64-musl@2.112.0'
  - '@supabase/cli-linux-arm64@2.112.0'
  - '@supabase/cli-linux-x64-musl@2.112.0'
  - '@supabase/cli-linux-x64@2.112.0'
  - '@supabase/cli-windows-arm64@2.112.0'
  - '@supabase/cli-windows-x64@2.112.0'
  - supabase@2.112.0
