// Generated by scripts/sync-database-contract.mjs. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  inkcre: {
    Tables: {
      agents: {
        Row: {
          created_at: string
          id: number
          max_model_calls_per_turn: number
          model: number
          name: string
          system_prompt: string
          tool_choice: Json | null
          tools: Array<string>
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: number
          max_model_calls_per_turn: number
          model: number
          name: string
          system_prompt: string
          tool_choice?: Json | null
          tools?: Array<string>
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: number
          max_model_calls_per_turn?: number
          model?: number
          name?: string
          system_prompt?: string
          tool_choice?: Json | null
          tools?: Array<string>
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'agents_model_fkey'
            columns: ['model']
            isOneToOne: false
            referencedRelation: 'ai_models'
            referencedColumns: ['id']
          },
        ]
      }
      ai_dialects: {
        Row: {
          config_schema: Json
          description: string
          id: string
        }
        Insert: {
          config_schema?: Json
          description: string
          id: string
        }
        Update: {
          config_schema?: Json
          description?: string
          id?: string
        }
        Relationships: []
      }
      ai_models: {
        Row: {
          capabilities: Json
          created_at: string
          enabled: boolean
          id: number
          name: string | null
          native_model_id: string
          provider: number
          updated_at: string
        }
        Insert: {
          capabilities: Json
          created_at?: string
          enabled?: boolean
          id?: number
          name?: string | null
          native_model_id: string
          provider: number
          updated_at?: string
        }
        Update: {
          capabilities?: Json
          created_at?: string
          enabled?: boolean
          id?: number
          name?: string | null
          native_model_id?: string
          provider?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'ai_models_provider_fkey'
            columns: ['provider']
            isOneToOne: false
            referencedRelation: 'ai_providers'
            referencedColumns: ['id']
          },
        ]
      }
      ai_providers: {
        Row: {
          config: Json
          created_at: string
          dialect: string
          enabled: boolean
          id: number
          name: string
          updated_at: string
        }
        Insert: {
          config?: Json
          created_at?: string
          dialect: string
          enabled?: boolean
          id?: number
          name: string
          updated_at?: string
        }
        Update: {
          config?: Json
          created_at?: string
          dialect?: string
          enabled?: boolean
          id?: number
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'ai_providers_dialect_fkey'
            columns: ['dialect']
            isOneToOne: false
            referencedRelation: 'ai_dialects'
            referencedColumns: ['id']
          },
        ]
      }
      block_embeddings: {
        Row: {
          block: number
          created_at: string
          embedding: Array<number>
          profile: number
          updated_at: string
        }
        Insert: {
          block?: number
          created_at?: string
          embedding: Array<number>
          profile?: number
          updated_at?: string
        }
        Update: {
          block?: number
          created_at?: string
          embedding?: Array<number>
          profile?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'block_embeddings_block_fkey'
            columns: ['block']
            isOneToOne: false
            referencedRelation: 'blocks'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'block_embeddings_profile_fkey'
            columns: ['profile']
            isOneToOne: false
            referencedRelation: 'embedding_profiles'
            referencedColumns: ['id']
          },
        ]
      }
      blocks: {
        Row: {
          content: string
          created_at: string | null
          id: number
          resolver: string
          storage: number | null
          updated_at: string | null
        }
        Insert: {
          content: string
          created_at?: string | null
          id?: number
          resolver: string
          storage?: number | null
          updated_at?: string | null
        }
        Update: {
          content?: string
          created_at?: string | null
          id?: number
          resolver?: string
          storage?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'blocks_storage_fkey'
            columns: ['storage']
            isOneToOne: false
            referencedRelation: 'storages'
            referencedColumns: ['id']
          },
        ]
      }
      configs: {
        Row: {
          created_at: string
          key: string
          schema: string
          updated_at: string
          value: Json
        }
        Insert: {
          created_at?: string
          key: string
          schema: string
          updated_at?: string
          value: Json
        }
        Update: {
          created_at?: string
          key?: string
          schema?: string
          updated_at?: string
          value?: Json
        }
        Relationships: []
      }
      embedding_profiles: {
        Row: {
          ai_model: number
          created_at: string
          dimensions: number
          id: number
          name: string | null
          updated_at: string
        }
        Insert: {
          ai_model: number
          created_at?: string
          dimensions: number
          id?: number
          name?: string | null
          updated_at?: string
        }
        Update: {
          ai_model?: number
          created_at?: string
          dimensions?: number
          id?: number
          name?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'embedding_profiles_ai_model_fkey'
            columns: ['ai_model']
            isOneToOne: false
            referencedRelation: 'ai_models'
            referencedColumns: ['id']
          },
        ]
      }
      extensions: {
        Row: {
          config: Json | null
          config_schema: Json | null
          enabled: Array<string>
          id: string
          nickname: string | null
          version: string
        }
        Insert: {
          config?: Json | null
          config_schema?: Json | null
          enabled?: Array<string>
          id: string
          nickname?: string | null
          version: string
        }
        Update: {
          config?: Json | null
          config_schema?: Json | null
          enabled?: Array<string>
          id?: string
          nickname?: string | null
          version?: string
        }
        Relationships: []
      }
      logs: {
        Row: {
          attributes: Json
          body: string
          id: number
          severity_number: number
          severity_text: string
          span_id: string | null
          timestamp: string
          trace_id: string | null
        }
        Insert: {
          attributes?: Json
          body: string
          id?: number
          severity_number: number
          severity_text: string
          span_id?: string | null
          timestamp?: string
          trace_id?: string | null
        }
        Update: {
          attributes?: Json
          body?: string
          id?: number
          severity_number?: number
          severity_text?: string
          span_id?: string | null
          timestamp?: string
          trace_id?: string | null
        }
        Relationships: []
      }
      peers: {
        Row: {
          capabilities: Json
          config: Json
          config_schema: Json
          created_at: string
          id: string
          labels: Array<string>
          lease_expires_at: string | null
          name: string
          updated_at: string
        }
        Insert: {
          capabilities?: Json
          config?: Json
          config_schema?: Json
          created_at?: string
          id?: string
          labels?: Array<string>
          lease_expires_at?: string | null
          name: string
          updated_at?: string
        }
        Update: {
          capabilities?: Json
          config?: Json
          config_schema?: Json
          created_at?: string
          id?: string
          labels?: Array<string>
          lease_expires_at?: string | null
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      relation_embeddings: {
        Row: {
          created_at: string
          embedding: Array<number>
          profile: number
          relation: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          embedding: Array<number>
          profile?: number
          relation?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          embedding?: Array<number>
          profile?: number
          relation?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'relation_embeddings_profile_fkey'
            columns: ['profile']
            isOneToOne: false
            referencedRelation: 'embedding_profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'relation_embeddings_relation_fkey'
            columns: ['relation']
            isOneToOne: false
            referencedRelation: 'relations'
            referencedColumns: ['id']
          },
        ]
      }
      relations: {
        Row: {
          content: string
          from_: number | null
          id: number
          to_: number | null
          updated_at: string | null
        }
        Insert: {
          content: string
          from_?: number | null
          id?: number
          to_?: number | null
          updated_at?: string | null
        }
        Update: {
          content?: string
          from_?: number | null
          id?: number
          to_?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'relations_from__fkey'
            columns: ['from_']
            isOneToOne: false
            referencedRelation: 'blocks'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'relations_to__fkey'
            columns: ['to_']
            isOneToOne: false
            referencedRelation: 'blocks'
            referencedColumns: ['id']
          },
        ]
      }
      sources: {
        Row: {
          collect_at: Json | null
          config: Json
          id: number
          nickname: string | null
          state: Json
          type: string | null
        }
        Insert: {
          collect_at?: Json | null
          config?: Json
          id?: number
          nickname?: string | null
          state?: Json
          type?: string | null
        }
        Update: {
          collect_at?: Json | null
          config?: Json
          id?: number
          nickname?: string | null
          state?: Json
          type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'sources_type_fkey'
            columns: ['type']
            isOneToOne: false
            referencedRelation: 'sources_types'
            referencedColumns: ['id']
          },
        ]
      }
      sources_collect_jobs: {
        Row: {
          closed_at: string | null
          config: Json | null
          created_at: string | null
          id: number
          source: number | null
          started_at: string | null
          state: Json | null
          status: 'pending' | 'running' | 'finished' | 'failed'
        }
        Insert: {
          closed_at?: string | null
          config?: Json | null
          created_at?: string | null
          id?: number
          source?: number | null
          started_at?: string | null
          state?: Json | null
          status?: 'pending' | 'running' | 'finished' | 'failed'
        }
        Update: {
          closed_at?: string | null
          config?: Json | null
          created_at?: string | null
          id?: number
          source?: number | null
          started_at?: string | null
          state?: Json | null
          status?: 'pending' | 'running' | 'finished' | 'failed'
        }
        Relationships: [
          {
            foreignKeyName: 'sources_collect_jobs_source_fkey'
            columns: ['source']
            isOneToOne: false
            referencedRelation: 'sources'
            referencedColumns: ['id']
          },
        ]
      }
      sources_types: {
        Row: {
          config_schema: Json
          description: string | null
          id: string
        }
        Insert: {
          config_schema?: Json
          description?: string | null
          id: string
        }
        Update: {
          config_schema?: Json
          description?: string | null
          id?: string
        }
        Relationships: []
      }
      storage_blobs: {
        Row: {
          data: string
          id: string
        }
        Insert: {
          data: string
          id?: string
        }
        Update: {
          data?: string
          id?: string
        }
        Relationships: []
      }
      storage_types: {
        Row: {
          config_schema: Json
          description: string
          id: string
        }
        Insert: {
          config_schema?: Json
          description: string
          id: string
        }
        Update: {
          config_schema?: Json
          description?: string
          id?: string
        }
        Relationships: []
      }
      storages: {
        Row: {
          config: Json
          id: number
          nickname: string | null
          type: string
        }
        Insert: {
          config?: Json
          id?: number
          nickname?: string | null
          type: string
        }
        Update: {
          config?: Json
          id?: number
          nickname?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: 'storages_type_fkey'
            columns: ['type']
            isOneToOne: false
            referencedRelation: 'storage_types'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<never, never>
    Functions: {
      create_storage_blob: {
        Args: never
        Returns: string
      }
      read_storage_blob: {
        Args: {
          blob_id: string
        }
        Returns: string
      }
      renew_peer_lease: {
        Args: {
          peer: string
          ttl_seconds: number
        }
        Returns: string
      }
    }
  }
}

export type InkcreSchema = Database['inkcre']
export type RelationName = keyof InkcreSchema['Tables']
export type RelationRow<Name extends RelationName> = InkcreSchema['Tables'][Name]['Row']
