// Generated by scripts/sync-database-contract.mjs. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  inkcre: {
    Tables: {
      block_embeddings: {
        Row: {
          embedding: Array<number>
          id: number
          updated_at: string | null
        }
        Insert: {
          embedding: Array<number>
          id?: number
          updated_at?: string | null
        }
        Update: {
          embedding?: Array<number>
          id?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'block_embeddings_id_fkey'
            columns: ['id']
            isOneToOne: false
            referencedRelation: 'blocks'
            referencedColumns: ['id']
          },
        ]
      }
      blocks: {
        Row: {
          content: string
          created_at: string | null
          id: number
          resolver: string
          storage: number | null
          updated_at: string | null
        }
        Insert: {
          content: string
          created_at?: string | null
          id?: number
          resolver: string
          storage?: number | null
          updated_at?: string | null
        }
        Update: {
          content?: string
          created_at?: string | null
          id?: number
          resolver?: string
          storage?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'blocks_storage_fkey'
            columns: ['storage']
            isOneToOne: false
            referencedRelation: 'storages'
            referencedColumns: ['id']
          },
        ]
      }
      clients: {
        Row: {
          config: Json
          config_schema: Json
          created_at: string | null
          id: string
          labels: Array<string> | null
          name: string
          rest_api_url: string | null
        }
        Insert: {
          config?: Json
          config_schema?: Json
          created_at?: string | null
          id?: string
          labels?: Array<string> | null
          name: string
          rest_api_url?: string | null
        }
        Update: {
          config?: Json
          config_schema?: Json
          created_at?: string | null
          id?: string
          labels?: Array<string> | null
          name?: string
          rest_api_url?: string | null
        }
        Relationships: []
      }
      extensions: {
        Row: {
          config: Json | null
          config_schema: Json | null
          enabled: Array<string>
          id: string
          nickname: string | null
          version: string
        }
        Insert: {
          config?: Json | null
          config_schema?: Json | null
          enabled?: Array<string>
          id: string
          nickname?: string | null
          version: string
        }
        Update: {
          config?: Json | null
          config_schema?: Json | null
          enabled?: Array<string>
          id?: string
          nickname?: string | null
          version?: string
        }
        Relationships: []
      }
      logs: {
        Row: {
          attributes: Json
          body: string
          id: number
          severity_number: number
          severity_text: string
          span_id: string | null
          timestamp: string
          trace_id: string | null
        }
        Insert: {
          attributes?: Json
          body: string
          id?: number
          severity_number: number
          severity_text: string
          span_id?: string | null
          timestamp?: string
          trace_id?: string | null
        }
        Update: {
          attributes?: Json
          body?: string
          id?: number
          severity_number?: number
          severity_text?: string
          span_id?: string | null
          timestamp?: string
          trace_id?: string | null
        }
        Relationships: []
      }
      relation_embeddings: {
        Row: {
          embedding: Array<number>
          id: number
          updated_at: string | null
        }
        Insert: {
          embedding: Array<number>
          id?: number
          updated_at?: string | null
        }
        Update: {
          embedding?: Array<number>
          id?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'relation_embeddings_id_fkey'
            columns: ['id']
            isOneToOne: false
            referencedRelation: 'relations'
            referencedColumns: ['id']
          },
        ]
      }
      relations: {
        Row: {
          content: string
          from_: number | null
          id: number
          to_: number | null
          updated_at: string | null
        }
        Insert: {
          content: string
          from_?: number | null
          id?: number
          to_?: number | null
          updated_at?: string | null
        }
        Update: {
          content?: string
          from_?: number | null
          id?: number
          to_?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'relations_from__fkey'
            columns: ['from_']
            isOneToOne: false
            referencedRelation: 'blocks'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'relations_to__fkey'
            columns: ['to_']
            isOneToOne: false
            referencedRelation: 'blocks'
            referencedColumns: ['id']
          },
        ]
      }
      sources: {
        Row: {
          collect_at: Json | null
          config: Json
          id: number
          nickname: string | null
          state: Json
          type: string | null
        }
        Insert: {
          collect_at?: Json | null
          config?: Json
          id?: number
          nickname?: string | null
          state?: Json
          type?: string | null
        }
        Update: {
          collect_at?: Json | null
          config?: Json
          id?: number
          nickname?: string | null
          state?: Json
          type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'sources_type_fkey'
            columns: ['type']
            isOneToOne: false
            referencedRelation: 'sources_types'
            referencedColumns: ['id']
          },
        ]
      }
      sources_collect_jobs: {
        Row: {
          closed_at: string | null
          config: Json | null
          created_at: string | null
          id: number
          source: number | null
          started_at: string | null
          state: Json | null
          status: 'pending' | 'running' | 'finished' | 'failed'
        }
        Insert: {
          closed_at?: string | null
          config?: Json | null
          created_at?: string | null
          id?: number
          source?: number | null
          started_at?: string | null
          state?: Json | null
          status?: 'pending' | 'running' | 'finished' | 'failed'
        }
        Update: {
          closed_at?: string | null
          config?: Json | null
          created_at?: string | null
          id?: number
          source?: number | null
          started_at?: string | null
          state?: Json | null
          status?: 'pending' | 'running' | 'finished' | 'failed'
        }
        Relationships: [
          {
            foreignKeyName: 'sources_collect_jobs_source_fkey'
            columns: ['source']
            isOneToOne: false
            referencedRelation: 'sources'
            referencedColumns: ['id']
          },
        ]
      }
      sources_types: {
        Row: {
          config_schema: Json
          description: string | null
          id: string
        }
        Insert: {
          config_schema?: Json
          description?: string | null
          id: string
        }
        Update: {
          config_schema?: Json
          description?: string | null
          id?: string
        }
        Relationships: []
      }
      storage_types: {
        Row: {
          config_schema: Json
          description: string
          id: string
        }
        Insert: {
          config_schema?: Json
          description: string
          id: string
        }
        Update: {
          config_schema?: Json
          description?: string
          id?: string
        }
        Relationships: []
      }
      storages: {
        Row: {
          config: Json
          id: number
          nickname: string | null
          type: string
        }
        Insert: {
          config?: Json
          id?: number
          nickname?: string | null
          type: string
        }
        Update: {
          config?: Json
          id?: number
          nickname?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: 'storages_type_fkey'
            columns: ['type']
            isOneToOne: false
            referencedRelation: 'storage_types'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<never, never>
    Functions: Record<never, never>
  }
}

export type InkcreSchema = Database['inkcre']
export type RelationName = keyof InkcreSchema['Tables']
export type RelationRow<Name extends RelationName> = InkcreSchema['Tables'][Name]['Row']
