// Generated by scripts/sync-database-contract.mjs. Do not edit by hand.

export const peerJwtContract = {
  algorithm: 'HS256',
  role: 'authenticated',
  issuer: 'inkcre-client',
  audience: 'inkcre-api',
  required_claims: ['role', 'iss', 'aud', 'iat', 'exp'],
  maximum_lifetime_seconds: 86400,
} as const

export const databaseRuntimeContract = {
  format: 1,
  revision: 'peer-database-runtime-v2',
  protocol: {
    format: 1,
    schema: 'inkcre',
  },
  jwt: peerJwtContract,
} as const

export type DatabaseRuntimeContract = typeof databaseRuntimeContract
