import { execFileSync } from 'node:child_process'
import { access, readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import { diagnoseDatabaseProvider, resolveDatabaseProviderConfig } from './database-provider.mjs'

const repoRoot = fileURLToPath(new URL('..', import.meta.url))
const jsonOutput = process.argv.includes('--json')
const configArgument = process.argv.indexOf('--config')
const portableConfigPath = configArgument >= 0 ? process.argv[configArgument + 1] : null
const checks = []

function record(name, status, detail) {
  checks.push({ name, status, detail })
}

async function exists(relativePath) {
  try {
    await access(`${repoRoot}/${relativePath}`)
    return true
  } catch {
    return false
  }
}

function commandVersion(command, args = ['--version']) {
  try {
    return execFileSync(command, args, {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      timeout: 5000,
    }).trim()
  } catch {
    return null
  }
}

const expectedNode = (await readFile(`${repoRoot}/.node-version`, 'utf8')).trim()
record(
  'node',
  process.version === `v${expectedNode}` ? 'ok' : 'error',
  `${process.version} (expected v${expectedNode})`
)

const rootPackage = JSON.parse(await readFile(`${repoRoot}/package.json`, 'utf8'))
const expectedPnpm = rootPackage.packageManager.replace('pnpm@', '')
const pnpmVersion = commandVersion('pnpm')
record(
  'pnpm',
  pnpmVersion === expectedPnpm ? 'ok' : 'error',
  `${pnpmVersion ?? 'missing'} (expected ${expectedPnpm})`
)

record(
  'lockfile',
  (await exists('pnpm-lock.yaml')) ? 'ok' : 'error',
  'pnpm-lock.yaml must be committed'
)
record(
  'wxt-generated-state',
  (await exists('apps/client-webext/.wxt/tsconfig.json')) ? 'ok' : 'error',
  'generated by the frozen-install postinstall'
)

const svcConfig = JSON.parse(await readFile(`${repoRoot}/svc.json`, 'utf8'))
record(
  'svc-config',
  svcConfig.schema_version === 2 && svcConfig.svc_version === '10.0.1' ? 'ok' : 'error',
  `schema ${svcConfig.schema_version}, adopted ${svcConfig.svc_version}`
)
record(
  'shared-docs',
  (await exists('docs/_shared/10-prd/index.md')) ? 'ok' : 'error',
  'docs/_shared must be initialized'
)

const localTargets = svcConfig.dev?.profiles?.local?.targets
record(
  'svc-dev-targets',
  svcConfig.dev?.profile === 'local' &&
    localTargets?.web?.scope === 'worktree' &&
    localTargets?.webext?.scope === 'worktree'
    ? 'ok'
    : 'error',
  localTargets ? Object.keys(localTargets).sort().join(', ') : 'missing local targets'
)

const svcVersion = commandVersion('svc')
if (svcVersion) {
  try {
    const status = JSON.parse(
      execFileSync('svc', ['status', '--json'], {
        cwd: repoRoot,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
        timeout: 10000,
      })
    )
    record('svc-runtime', status.healthy ? 'ok' : 'error', svcVersion)
  } catch {
    record('svc-runtime', 'error', `${svcVersion}; status failed`)
  }
} else {
  record('svc-runtime', 'warning', 'not on PATH; install sustainable-vibe-coding==10.0.1')
}

try {
  const provider = resolveDatabaseProviderConfig()
  const diagnostic = diagnoseDatabaseProvider(provider)
  const endpoint = provider.kind === 'ssh' ? ` via ${provider.target}` : ''
  record(
    'database-provider',
    'ok',
    `${provider.kind}${endpoint}; engine ${diagnostic.engine}; compose ${diagnostic.compose}`
  )
} catch {
  record(
    'database-provider',
    'error',
    'selected local or SSH Docker provider is unavailable; inspect svc.local.json and SSH/Docker state'
  )
}

const corePin = JSON.parse(await readFile(`${repoRoot}/contracts/core-py.json`, 'utf8'))
const coreContract = JSON.parse(
  await readFile(`${repoRoot}/contracts/core-py-contract.json`, 'utf8')
)
const productionProfile = JSON.parse(
  await readFile(`${repoRoot}/deploy/profiles/production.json`, 'utf8')
)
const legacyEndpoints = JSON.parse(
  await readFile(`${repoRoot}/deploy/profiles/legacy-endpoints.json`, 'utf8')
)
record(
  'core-runtime-image',
  corePin.image?.includes('@sha256:') ? 'ok' : 'error',
  `${corePin.image} (${corePin.source_revision})`
)
record(
  'database-contract',
  coreContract.revision === corePin.contract_revision ? 'ok' : 'error',
  `${coreContract.revision}; schema ${coreContract.protocol?.schema}; ${Object.keys(coreContract.protocol?.relations ?? {}).length} relations`
)
record(
  'database-readiness-profile',
  coreContract.profiles?.includes('development') ? 'ok' : 'error',
  'development'
)
record(
  'config-provenance',
  'ok',
  `browser-local; canonical ${productionProfile.environment} profile`
)

if (portableConfigPath) {
  try {
    const portableConfig = JSON.parse(await readFile(portableConfigPath, 'utf8'))
    const endpoint = new URL(portableConfig.metaConfig?.INKCRE_PGREST_URL)
    const isLegacy =
      legacyEndpoints.postgrest_hosts.includes(endpoint.hostname) ||
      endpoint.hostname.startsWith('inkcre-pgrst-')
    record(
      'legacy-endpoint',
      isLegacy ? 'error' : 'ok',
      isLegacy
        ? `retired host ${endpoint.hostname}; import the canonical production profile`
        : `portable config uses ${endpoint.hostname}`
    )
  } catch {
    record(
      'legacy-endpoint',
      'error',
      'the --config file is absent, invalid, or lacks a PostgREST URL'
    )
  }
} else {
  record(
    'legacy-endpoint',
    'warning',
    'browser storage is not CLI-readable; pass --config <portable-export.json> to inspect'
  )
}

const expectedPortless = rootPackage.devDependencies.portless
const portlessVersion = commandVersion(`${repoRoot}/node_modules/.bin/portless`)
record(
  'portless',
  portlessVersion === expectedPortless ? 'ok' : 'error',
  `${portlessVersion ?? 'missing'} (expected ${expectedPortless})`
)

try {
  execFileSync(process.execPath, ['scripts/check-local-runtime-contract.mjs'], {
    cwd: repoRoot,
    stdio: ['ignore', 'pipe', 'ignore'],
    timeout: 10000,
  })
  record('local-runtime-contract', 'ok', 'static config and worktree targets verified')
} catch {
  record('local-runtime-contract', 'error', 'run pnpm check:runtime for details')
}

try {
  execFileSync(process.execPath, ['scripts/check-database-contract.mjs'], {
    cwd: repoRoot,
    stdio: ['ignore', 'pipe', 'ignore'],
    timeout: 10000,
  })
  record('database-contract-gate', 'ok', 'pin, profile, generated types, and Compose agree')
} catch {
  record('database-contract-gate', 'error', 'run pnpm check:database for details')
}

const fatal = checks.filter((check) => check.status === 'error')
const result = {
  ok: fatal.length === 0,
  phase: 4,
  checks,
}

if (jsonOutput) {
  console.log(JSON.stringify(result, null, 2))
} else {
  for (const check of checks) {
    console.log(`[${check.status.toUpperCase()}] ${check.name}: ${check.detail}`)
  }
}

process.exitCode = result.ok ? 0 : 1
