import { execFileSync } from 'node:child_process'
import { access, readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import { diagnoseDatabaseProvider, resolveDatabaseProviderConfig } from './database-provider.mjs'

const repoRoot = fileURLToPath(new URL('..', import.meta.url))
const jsonOutput = process.argv.includes('--json')
const configArgument = process.argv.indexOf('--config')
const portableConfigPath = configArgument >= 0 ? process.argv[configArgument + 1] : null
const checks = []

function record(name, status, detail) {
  checks.push({ name, status, detail })
}

async function exists(relativePath) {
  try {
    await access(`${repoRoot}/${relativePath}`)
    return true
  } catch {
    return false
  }
}

function commandVersion(command, args = ['--version']) {
  try {
    return execFileSync(command, args, {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      timeout: 5000,
    }).trim()
  } catch {
    return null
  }
}

const rootPackage = JSON.parse(await readFile(`${repoRoot}/package.json`, 'utf8'))
const expectedNode = rootPackage.devEngines?.runtime?.version
record(
  'node',
  expectedNode && process.version === `v${expectedNode}` ? 'ok' : 'error',
  `${process.version} (expected ${expectedNode ? `v${expectedNode}` : 'devEngines.runtime'})`
)

const expectedPnpm = rootPackage.packageManager.replace('pnpm@', '')
const pnpmVersion = commandVersion('pnpm')
record(
  'pnpm',
  pnpmVersion === expectedPnpm ? 'ok' : 'error',
  `${pnpmVersion ?? 'missing'} (expected ${expectedPnpm})`
)

record(
  'lockfile',
  (await exists('pnpm-lock.yaml')) ? 'ok' : 'error',
  'pnpm-lock.yaml must be committed'
)
record(
  'wxt-generated-state',
  (await exists('apps/client-webext/.wxt/tsconfig.json')) ? 'ok' : 'error',
  'generated by the frozen-install postinstall'
)

const svcConfig = JSON.parse(await readFile(`${repoRoot}/svc.json`, 'utf8'))
record(
  'svc-config',
  svcConfig.schema_version === 2 && svcConfig.svc_version === '10.0.1' ? 'ok' : 'error',
  `schema ${svcConfig.schema_version}, adopted ${svcConfig.svc_version}`
)
record(
  'shared-docs',
  (await exists('docs/_shared/10-prd/index.md')) ? 'ok' : 'error',
  'docs/_shared must be initialized'
)

const localTargets = svcConfig.dev?.profiles?.local?.targets
record(
  'svc-dev-targets',
  svcConfig.dev?.profile === 'local' &&
    localTargets?.web?.scope === 'worktree' &&
    localTargets?.['web-ui']?.scope === 'worktree' &&
    localTargets?.webext?.scope === 'worktree'
    ? 'ok'
    : 'error',
  localTargets ? Object.keys(localTargets).sort().join(', ') : 'missing local targets'
)

const svcVersion = commandVersion('svc')
if (svcVersion) {
  try {
    const status = JSON.parse(
      execFileSync('svc', ['status', '--json'], {
        cwd: repoRoot,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
        timeout: 10000,
      })
    )
    record('svc-runtime', status.healthy ? 'ok' : 'error', svcVersion)
  } catch {
    record('svc-runtime', 'error', `${svcVersion}; status failed`)
  }
} else {
  record('svc-runtime', 'warning', 'not on PATH; install sustainable-vibe-coding==10.0.1')
}

try {
  const provider = resolveDatabaseProviderConfig()
  const diagnostic = diagnoseDatabaseProvider(provider)
  const endpoint =
    provider.kind === 'ssh'
      ? ` via ${provider.target}`
      : provider.kind === 'external'
        ? ` ${diagnostic.owner_repository}/${diagnostic.runtime_instance} on ${diagnostic.daemon_id}`
        : ''
  record(
    'database-provider',
    'ok',
    `${provider.kind}${endpoint}; engine ${diagnostic.engine}; compose ${diagnostic.compose}`
  )
} catch {
  record(
    'database-provider',
    'error',
    'selected local, SSH, or external core-py database provider is unavailable; inspect svc.local.json and runtime state'
  )
}

const coreRelease = JSON.parse(await readFile(`${repoRoot}/contracts/core-release.json`, 'utf8'))
const databaseCompatibility = JSON.parse(
  await readFile(`${repoRoot}/packages/core/src/database/runtime-contract.generated.json`, 'utf8')
)
record(
  'core-runtime-release',
  coreRelease.stable_image === 'ghcr.io/inkcre/core-py:stable' ? 'ok' : 'error',
  coreRelease.stable_image
)
record(
  'database-contract',
  databaseCompatibility.protocol?.schema === 'inkcre' ? 'ok' : 'error',
  `${databaseCompatibility.revision}; schema ${databaseCompatibility.protocol?.schema}; Supabase-generated types checked in`
)
record('config-provenance', 'ok', 'browser-local; no checked-in environment profile')

if (portableConfigPath) {
  try {
    const portableConfig = JSON.parse(await readFile(portableConfigPath, 'utf8'))
    const endpoint = new URL(portableConfig.metaConfig?.INKCRE_PGREST_URL)
    record(
      'portable-config',
      endpoint.protocol === 'https:' || endpoint.protocol === 'http:' ? 'ok' : 'error',
      `explicit PostgREST endpoint ${endpoint.hostname}`
    )
  } catch {
    record(
      'portable-config',
      'error',
      'the --config file is absent, invalid, or lacks a PostgREST URL'
    )
  }
} else {
  record(
    'portable-config',
    'warning',
    'browser storage is not CLI-readable; pass --config <portable-export.json> to inspect'
  )
}

const expectedPortless = rootPackage.devDependencies.portless
const portlessVersion = commandVersion(`${repoRoot}/node_modules/.bin/portless`)
record(
  'portless',
  portlessVersion === expectedPortless ? 'ok' : 'error',
  `${portlessVersion ?? 'missing'} (expected ${expectedPortless})`
)

try {
  execFileSync(process.execPath, ['scripts/check-local-runtime-contract.mjs'], {
    cwd: repoRoot,
    stdio: ['ignore', 'pipe', 'ignore'],
    timeout: 10000,
  })
  record('local-runtime-contract', 'ok', 'static config and worktree targets verified')
} catch {
  record('local-runtime-contract', 'error', 'run pnpm check:runtime for details')
}

try {
  execFileSync(process.execPath, ['scripts/check-database-contract.mjs'], {
    cwd: repoRoot,
    stdio: ['ignore', 'pipe', 'ignore'],
    timeout: 10000,
  })
  record('database-contract-gate', 'ok', 'pin, generated runtime/types, and Compose agree')
} catch {
  record('database-contract-gate', 'error', 'run pnpm check:database for details')
}

const fatal = checks.filter((check) => check.status === 'error')
const result = {
  ok: fatal.length === 0,
  phase: 4,
  checks,
}

if (jsonOutput) {
  console.log(JSON.stringify(result, null, 2))
} else {
  for (const check of checks) {
    console.log(`[${check.status.toUpperCase()}] ${check.name}: ${check.detail}`)
  }
}

process.exitCode = result.ok ? 0 : 1
