import { execFileSync } from 'node:child_process'
import { access, readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const repoRoot = fileURLToPath(new URL('..', import.meta.url))
const jsonOutput = process.argv.includes('--json')
const checks = []

function record(name, status, detail) {
  checks.push({ name, status, detail })
}

async function exists(relativePath) {
  try {
    await access(`${repoRoot}/${relativePath}`)
    return true
  } catch {
    return false
  }
}

function commandVersion(command, args = ['--version']) {
  try {
    return execFileSync(command, args, {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      timeout: 5000,
    }).trim()
  } catch {
    return null
  }
}

const expectedNode = (await readFile(`${repoRoot}/.node-version`, 'utf8')).trim()
record(
  'node',
  process.version === `v${expectedNode}` ? 'ok' : 'error',
  `${process.version} (expected v${expectedNode})`
)

const rootPackage = JSON.parse(await readFile(`${repoRoot}/package.json`, 'utf8'))
const expectedPnpm = rootPackage.packageManager.replace('pnpm@', '')
const pnpmVersion = commandVersion('pnpm')
record(
  'pnpm',
  pnpmVersion === expectedPnpm ? 'ok' : 'error',
  `${pnpmVersion ?? 'missing'} (expected ${expectedPnpm})`
)

record(
  'lockfile',
  (await exists('pnpm-lock.yaml')) ? 'ok' : 'error',
  'pnpm-lock.yaml must be committed'
)
record(
  'wxt-generated-state',
  (await exists('apps/client-webext/.wxt/tsconfig.json')) ? 'ok' : 'error',
  'generated by the frozen-install postinstall'
)

const svcConfig = JSON.parse(await readFile(`${repoRoot}/svc.json`, 'utf8'))
record(
  'svc-config',
  svcConfig.schema_version === 2 && svcConfig.svc_version === '10.0.1' ? 'ok' : 'error',
  `schema ${svcConfig.schema_version}, adopted ${svcConfig.svc_version}`
)
record(
  'shared-docs',
  (await exists('docs/_shared/10-prd/index.md')) ? 'ok' : 'error',
  'docs/_shared must be initialized'
)

const svcVersion = commandVersion('svc')
if (svcVersion) {
  try {
    const status = JSON.parse(
      execFileSync('svc', ['status', '--json'], {
        cwd: repoRoot,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
        timeout: 10000,
      })
    )
    record('svc-runtime', status.healthy ? 'ok' : 'error', svcVersion)
  } catch {
    record('svc-runtime', 'error', `${svcVersion}; status failed`)
  }
} else {
  record('svc-runtime', 'warning', 'not on PATH; install sustainable-vibe-coding==10.0.1')
}

const dockerVersion = commandVersion('docker')
record(
  'docker',
  dockerVersion ? 'ok' : 'warning',
  dockerVersion ?? 'not installed; Docker/PostgREST capability is owned by Phase 3'
)

record('portless', 'warning', 'worktree-local URL capability is owned by Phase 3')

const fatal = checks.filter((check) => check.status === 'error')
const result = {
  ok: fatal.length === 0,
  phase: 2,
  checks,
}

if (jsonOutput) {
  console.log(JSON.stringify(result, null, 2))
} else {
  for (const check of checks) {
    console.log(`[${check.status.toUpperCase()}] ${check.name}: ${check.detail}`)
  }
}

process.exitCode = result.ok ? 0 : 1
